title: Windows 12 Documentation
description: Windows12 Docs
theme: just-the-docs

url: https://tangyuan.github.io/windows12-doc/

aux_links:
  Windows12 Docs Github : https://github.com/tangyuan0821/windows12-doc

plugins:
  - jekyll-default-layout

